// <auto-generated />
namespace AccountingTestWPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitiateAccountingDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitiateAccountingDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202112260933378_InitiateAccountingDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
